common:
  clusterName: prd-sbg5-1

stats:
  enabled: true
  name: stats
  replicaCount: 1
  image:
    repository: ghcr.io/1oopio/miningcore
    pullPolicy: IfNotPresent
    tag: "pr-5"
  affinity: {}

payout:
  enabled: true
  name: payout
  image:
    repository: ghcr.io/1oopio/miningcore
    pullPolicy: IfNotPresent
    tag: "pr-5"

config:
  pool:
    daemons:
      - user: test
        password: test
        host: 10.200.119.113
        port: 7229

postgresql:
  enabled: true